package main.java.com.careHubApps.view.dokter;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.java.com.careHubApps.DatabaseConnection;
import main.java.com.careHubApps.controller.DokterController;
import main.java.com.careHubApps.model.DokterModel;
import resources.components.ComboBox;
import resources.components.CustomTextField;
import resources.components.RoundedPanel;
import resources.components.ShadowPanel;

/**
 *
 * @author ASUS
 */
public class TambahDokterView extends javax.swing.JFrame {

    DokterController dokterController;
    DatabaseConnection dbConnection;
    DokterModel dokterModel;

    /**
     * Creates new form TambahObatView
     */
    public TambahDokterView() {
        initComponents();

        dokterController = new DokterController();
        dbConnection = new DatabaseConnection();
//        dokterModel = new DokterModel(dokterModel.getId(),dokterModel.getNama(), dokterModel.getSpesialis(), dokterModel.getNoTelpon(), dokterModel.getAlamat());

        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);

        try {
            File poppinsRegular = new File("src/resources/assets/fonts/Poppins-Regular.ttf");
            File poppinsSemiBold = new File("src/resources/assets/fonts/Poppins-SemiBold.ttf");

            Font titleTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(20f);
            Font labelInputTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(14f);
            Font labelButtonStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(14f);
            Font txtFieldStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsRegular).deriveFont(14f);

            titleDataObat.setFont(titleTxtStyle);

            labelInputNama.setFont(labelInputTxtStyle);
            labelInputStok.setFont(labelInputTxtStyle);
            labelInputHarga.setFont(labelInputTxtStyle);

            txtFieldNamaDokter.setFont(txtFieldStyle);
            txtFieldAlamat.setFont(txtFieldStyle);
            comboSpesialis.setFont(labelInputTxtStyle);
            txtFieldTelpon.setFont(txtFieldStyle);

            labelButtonSimpan.setFont(labelButtonStyle);

        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        bodyPanel = new ShadowPanel(8, Color.decode("#DFDFDF"));
        txtFieldNamaDokter = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "Nama Dokter", 8);
        labelInputNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelInputHarga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldTelpon = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "081234567890", 8);
        txtFieldAlamat = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "contoh: Jl. Kenangan No. 1, Kota Bandung", 8);
        labelInputStok = new javax.swing.JLabel();
        simpanButton = new RoundedPanel(12, Color.decode("#508D4E"));
        labelButtonSimpan = new javax.swing.JLabel();
        comboSpesialis = new ComboBox("Pilih Spesialis");
        headerPanel = new ShadowPanel(8, Color.decode("#DFDFDF"));
        titleDataObat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 660));
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldNamaDokter.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldNamaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 430, 40));

        labelInputNama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputNama.setText("Nama Dokter");
        bodyPanel.add(labelInputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        bodyPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 10, -1));

        labelInputHarga.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputHarga.setText("No Telpon");
        bodyPanel.add(labelInputHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");
        bodyPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 10));

        txtFieldTelpon.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 430, 40));

        txtFieldAlamat.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 430, 40));

        labelInputStok.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputStok.setText("Alamat");
        bodyPanel.add(labelInputStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 20));

        simpanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanButtonMouseClicked(evt);
            }
        });

        labelButtonSimpan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelButtonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonSimpan.setText("Simpan Data");

        javax.swing.GroupLayout simpanButtonLayout = new javax.swing.GroupLayout(simpanButton);
        simpanButton.setLayout(simpanButtonLayout);
        simpanButtonLayout.setHorizontalGroup(
            simpanButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpanButtonLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(labelButtonSimpan)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        simpanButtonLayout.setVerticalGroup(
            simpanButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpanButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelButtonSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanel.add(simpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 430, 40));

        comboSpesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umum", "Gigi", "THT", "Mata" }));
        comboSpesialis.setSelectedIndex(-1);
        bodyPanel.add(comboSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 430, 40));

        mainPanel.add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 500, 540));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleDataObat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        titleDataObat.setText("Tambah Data Dokter");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/doctor_icon.png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(105, 105, 105)
                .addComponent(titleDataObat)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(titleDataObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, 70));

        getContentPane().add(mainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanButtonMouseClicked
        String namaDokter = txtFieldNamaDokter.getText();
        Object spesialisObj = comboSpesialis.getSelectedItem();
        String telpon = txtFieldTelpon.getText();
        String alamat = txtFieldAlamat.getText();

        // Validasi input
        if (namaDokter.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama dokter tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (spesialisObj == null || spesialisObj.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Spesialis tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String spesialis = spesialisObj.toString();

        if (telpon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomor telepon tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!telpon.matches("\\d{10,12}")) { // Contoh validasi nomor telepon harus angka dan panjang 10-12 digit
            JOptionPane.showMessageDialog(this, "Nomor telepon harus berupa angka dan panjang 10-12 digit", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        dokterModel = new DokterModel(null, namaDokter, spesialis, telpon, alamat);

        if (dokterController.tambahDokter(dokterModel)) {
            JOptionPane.showMessageDialog(this, "Data dokter berhasil disimpan dengan ID: " + dokterModel.getId());
            clearInput();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data dokter");
        }
    }//GEN-LAST:event_simpanButtonMouseClicked

    private void clearInput() {
        txtFieldNamaDokter.setText("");
        txtFieldTelpon.setText("");
        txtFieldAlamat.setText("");
        comboSpesialis.setSelectedIndex(-1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahDokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahDokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahDokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahDokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahDokterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JComboBox<String> comboSpesialis;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelButtonSimpan;
    private javax.swing.JLabel labelInputHarga;
    private javax.swing.JLabel labelInputNama;
    private javax.swing.JLabel labelInputStok;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel simpanButton;
    private javax.swing.JLabel titleDataObat;
    private javax.swing.JTextField txtFieldAlamat;
    private javax.swing.JTextField txtFieldNamaDokter;
    private javax.swing.JTextField txtFieldTelpon;
    // End of variables declaration//GEN-END:variables
}
