package main.java.com.careHubApps.view.obat;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.java.com.careHubApps.DatabaseConnection;
import main.java.com.careHubApps.controller.ObatController;
import main.java.com.careHubApps.model.ObatModel;
import main.java.com.careHubApps.model.PasienModel;
import resources.components.ComboBox;
import resources.components.CustomTextField;
import resources.components.RoundedPanel;
import resources.components.ShadowPanel;

/**
 *
 * @author ASUS
 */
public class EditObatView extends javax.swing.JFrame {

    ObatController obatController;
    DatabaseConnection dbConnection;
    ObatModel obatModel;
    
    /**
     * Creates new form TambahObatView
     * @param obatModel
     */
    
    public EditObatView(ObatModel obatModel) {
        initComponents();
        
        this.obatModel = obatModel;
        
        obatController = new ObatController();
        dbConnection = new DatabaseConnection();
        comboKategori.setSelectedIndex(-1);
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        
        loadData(obatModel);
        
        try {
            File poppinsRegular = new File("src/resources/assets/fonts/Poppins-Regular.ttf");
            File poppinsSemiBold = new File("src/resources/assets/fonts/Poppins-SemiBold.ttf");
           
            Font titleTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(20f);
            Font labelInputTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(14f);
            Font labelButtonStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(14f);
            Font txtFieldStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsRegular).deriveFont(14f);
            
            
            titleDataObat.setFont(titleTxtStyle);
            
            labelInputNama.setFont(labelInputTxtStyle);
            labelInputStok.setFont(labelInputTxtStyle);
            labelInputHarga.setFont(labelInputTxtStyle);
            labelInputTgl.setFont(labelInputTxtStyle);
            
            txtFieldNamaObat.setFont(txtFieldStyle);
            txtFieldStok.setFont(txtFieldStyle);
            txtFieldTglExp.setFont(txtFieldStyle);
            txtFieldHarga.setFont(txtFieldStyle);
            
            comboKategori.setFont(labelInputTxtStyle);
            
            labelButtonSimpan.setFont(labelButtonStyle);
            
            
        } catch (FontFormatException | IOException e){
            e.printStackTrace();
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        bodyPanel = new ShadowPanel(8, Color.decode("#DFDFDF"));
        txtFieldNamaObat = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "Nama Obat", 8);
        labelInputNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelInputTgl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldTglExp = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "DD/MM/YYYY", 8);
        labelInputHarga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldHarga = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "contoh: 20000", 8);
        txtFieldStok = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "contoh: 10", 8);
        labelInputStok = new javax.swing.JLabel();
        simpanButton = new RoundedPanel(12, Color.decode("#508D4E"));
        labelButtonSimpan = new javax.swing.JLabel();
        comboKategori = new ComboBox("Kategori Obat");
        headerPanel = new ShadowPanel(8, Color.decode("#DFDFDF"));
        titleDataObat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 660));
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldNamaObat.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldNamaObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 430, 40));

        labelInputNama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputNama.setText("Nama Obat");
        bodyPanel.add(labelInputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        bodyPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 10, -1));

        labelInputTgl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputTgl.setText("Expired");
        bodyPanel.add(labelInputTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        bodyPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 10));

        txtFieldTglExp.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldTglExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 40));

        labelInputHarga.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputHarga.setText("Harga");
        bodyPanel.add(labelInputHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");
        bodyPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, 10));

        txtFieldHarga.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 40));

        txtFieldStok.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 200, 40));

        labelInputStok.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputStok.setText("Jumlah Stok");
        bodyPanel.add(labelInputStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, 20));

        simpanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanButtonMouseClicked(evt);
            }
        });

        labelButtonSimpan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelButtonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonSimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelButtonSimpan.setText("Simpan Perubahan");

        javax.swing.GroupLayout simpanButtonLayout = new javax.swing.GroupLayout(simpanButton);
        simpanButton.setLayout(simpanButtonLayout);
        simpanButtonLayout.setHorizontalGroup(
            simpanButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelButtonSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        simpanButtonLayout.setVerticalGroup(
            simpanButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelButtonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bodyPanel.add(simpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 430, 40));

        comboKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgesik", "Antibiotik", "Antihistamin", "Antipiretik", "Antihipertensi", "Antidepresan", "Antidiabetik", "Bronkodilator", "Antiemetik", "Antifungal" }));
        comboKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKategoriActionPerformed(evt);
            }
        });
        bodyPanel.add(comboKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 420, 40));

        mainPanel.add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 500, 540));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleDataObat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        titleDataObat.setText("Edit Data Obat");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/medicine_icon.png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(105, 105, 105)
                .addComponent(titleDataObat)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(titleDataObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, 70));

        getContentPane().add(mainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanButtonMouseClicked
        // TODO add your handling code here:
        String namaObat = txtFieldNamaObat.getText();
        String kategori = comboKategori.getSelectedItem().toString();
        String exp = txtFieldTglExp.getText();
        int harga = Integer.valueOf(txtFieldHarga.getText());
        int stok = Integer.valueOf(txtFieldStok.getText());
        
        
//        if (nama.isEmpty() || tglLahir.isEmpty() || noTelpon.isEmpty() || jenisKelamin.isEmpty() || golDarah.isEmpty() || dokter.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua field!", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }

        obatModel = new ObatModel(obatModel.getId(), namaObat, kategori, exp, harga, stok);
        boolean isUpdated = obatController.updateObat(obatModel);
        
        if (isUpdated) {
            JOptionPane.showMessageDialog(this, "Data obat berhasil diupdate!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate data pasien!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_simpanButtonMouseClicked

    private void comboKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKategoriActionPerformed

    private void clearInput(){
        txtFieldNamaObat.setText("");
        txtFieldHarga.setText("");
        txtFieldStok.setText("");
        txtFieldTglExp.setText("");
        comboKategori.setSelectedIndex(-1);
    }
    
    private void loadData(ObatModel obat) {
        txtFieldNamaObat.setText(obat.getNama());
        txtFieldTglExp.setText(obat.getExp());
        txtFieldHarga.setText(String.valueOf(obat.getHarga()));
        txtFieldStok.setText(String.valueOf(obat.getStok()));
        comboKategori.setSelectedItem(obat.getKategori());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JComboBox<String> comboKategori;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelButtonSimpan;
    private javax.swing.JLabel labelInputHarga;
    private javax.swing.JLabel labelInputNama;
    private javax.swing.JLabel labelInputStok;
    private javax.swing.JLabel labelInputTgl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel simpanButton;
    private javax.swing.JLabel titleDataObat;
    private javax.swing.JTextField txtFieldHarga;
    private javax.swing.JTextField txtFieldNamaObat;
    private javax.swing.JTextField txtFieldStok;
    private javax.swing.JTextField txtFieldTglExp;
    // End of variables declaration//GEN-END:variables
}
