/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.careHubApps.view.pasien;

import java.awt.Font;
import java.io.File;
import resources.components.ShadowPanel;
import resources.components.RoundedPanel;
import resources.components.CustomTextField;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.java.com.careHubApps.DatabaseConnection;
import main.java.com.careHubApps.controller.PasienController;
import main.java.com.careHubApps.model.PasienModel;
import resources.components.ComboBox;

/**
 *
 * @author ASUS
 */
public class DaftarPanel extends javax.swing.JPanel {

    PasienController pasienController;
    DatabaseConnection dbConnection;

    // Inisialisasi variabel warna
    String primaryColor = "#1A5319";
    String hoverColor = "#00000";

    /**
     * Creates new form HomePanel
     */
    public DaftarPanel() {
        initComponents();

        pasienController = new PasienController();
        dbConnection = new DatabaseConnection();

        comboGolDarah.setSelectedIndex(-1);
        comboJenKel.setSelectedIndex(-1);
        comboDokter.setSelectedIndex(-1);

        try {
            File poppinsRegular = new File("src/resources/assets/fonts/Poppins-Regular.ttf");
            File poppinsSemiBold = new File("src/resources/assets/fonts/Poppins-SemiBold.ttf");

            Font titleTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(20f);
            Font labelInputTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(14f);
            Font labelButtonStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(14f);
            Font txtFieldStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsRegular).deriveFont(14f);

            titleDaftarPanel.setFont(titleTxtStyle);

            labelInputNama.setFont(labelInputTxtStyle);
            labelInputEmail.setFont(labelInputTxtStyle);
            labelInputHP.setFont(labelInputTxtStyle);
            labelInputTgl.setFont(labelInputTxtStyle);
            labelButtonSimpan.setFont(labelButtonStyle);

            comboJenKel.setFont(labelButtonStyle);
            comboGolDarah.setFont(labelButtonStyle);
            comboDokter.setFont(labelButtonStyle);

            txtFieldNama.setFont(txtFieldStyle);
            txtFieldTglLahir.setFont(txtFieldStyle);
            txtFieldEmail.setFont(txtFieldStyle);
            txtFieldHp.setFont(txtFieldStyle);

        } catch (Exception e) {
            e.printStackTrace();
        }

        setupHoverEffect(simpanButton, Color.decode(primaryColor), Color.decode(hoverColor));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        cardHeader = new ShadowPanel(6, Color.decode("#DFDFDF"));
        titleDaftarPanel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bodyPanel = new ShadowPanel(8, Color.decode("#DFDFDF"));
        txtFieldNama = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "Your Name", 8);
        labelInputNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelInputTgl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldTglLahir = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "DD/MM/YYYY", 8);
        jLabel5 = new javax.swing.JLabel();
        labelInputHP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldHp = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "081234567890", 8);
        txtFieldEmail = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "yourmail@example", 8);
        labelInputEmail = new javax.swing.JLabel();
        simpanButton = new RoundedPanel(12, Color.decode("#508D4E"));
        labelButtonSimpan = new javax.swing.JLabel();
        comboGolDarah = new ComboBox("Golongan Darah");
        comboJenKel = new ComboBox("Jenis Kelamin");
        comboDokter = new ComboBox("Pilih Layanan");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardHeader.setBackground(new java.awt.Color(255, 255, 255));

        titleDaftarPanel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        titleDaftarPanel.setText("Form Pendaftaran");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/form_icon.png"))); // NOI18N

        javax.swing.GroupLayout cardHeaderLayout = new javax.swing.GroupLayout(cardHeader);
        cardHeader.setLayout(cardHeaderLayout);
        cardHeaderLayout.setHorizontalGroup(
            cardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHeaderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(titleDaftarPanel)
                .addContainerGap(767, Short.MAX_VALUE))
        );
        cardHeaderLayout.setVerticalGroup(
            cardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardHeaderLayout.createSequentialGroup()
                .addGroup(cardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(titleDaftarPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(cardHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1000, 60));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldNama.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 430, 40));

        labelInputNama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputNama.setText("Nama Lengkap");
        bodyPanel.add(labelInputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        bodyPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 10, -1));

        labelInputTgl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputTgl.setText("Tanggal Lahir");
        bodyPanel.add(labelInputTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        bodyPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 10));

        txtFieldTglLahir.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/doctor_illustration.png"))); // NOI18N
        bodyPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 330, 450));

        labelInputHP.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputHP.setText("Nomor HP");
        bodyPanel.add(labelInputHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");
        bodyPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, 10));

        txtFieldHp.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 40));

        txtFieldEmail.setMargin(new java.awt.Insets(4, 4, 4, 4));
        bodyPanel.add(txtFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 200, 40));

        labelInputEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelInputEmail.setText("Email");
        bodyPanel.add(labelInputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, 20));

        simpanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanButtonMouseClicked(evt);
            }
        });

        labelButtonSimpan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelButtonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonSimpan.setText("Simpan Data");

        javax.swing.GroupLayout simpanButtonLayout = new javax.swing.GroupLayout(simpanButton);
        simpanButton.setLayout(simpanButtonLayout);
        simpanButtonLayout.setHorizontalGroup(
            simpanButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpanButtonLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(labelButtonSimpan)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        simpanButtonLayout.setVerticalGroup(
            simpanButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpanButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelButtonSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanel.add(simpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 420, 40));

        comboGolDarah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O", "Tidak Tahu" }));
        bodyPanel.add(comboGolDarah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 210, 40));

        comboJenKel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        bodyPanel.add(comboJenKel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 40));

        comboDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umum", "Gigi", "THT", "Mata" }));
        bodyPanel.add(comboDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, 40));

        mainPanel.add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1000, 590));

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanButtonMouseClicked
        // TODO add your handling code here:
        tambahPasien();
    }//GEN-LAST:event_simpanButtonMouseClicked

    private void tambahPasien() {
        String nama = txtFieldNama.getText().trim();
        String tglLahir = txtFieldTglLahir.getText().trim();
        String noTelpon = txtFieldHp.getText().trim();
        String email = txtFieldEmail.getText().trim();

        // Dapatkan nilai combo box dengan pengecekan null
        Object jenKelObj = comboJenKel.getSelectedItem();
        Object golDarObj = comboGolDarah.getSelectedItem();
        Object dokterObj = comboDokter.getSelectedItem();

        // Validasi input
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tglLahir.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal lahir tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (noTelpon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomor telepon tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!noTelpon.matches("\\d{10,12}")) { // Contoh validasi nomor telepon harus angka dan panjang 10-12 digit
            JOptionPane.showMessageDialog(this, "Nomor telepon harus berupa angka dan panjang 10-12 digit", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (jenKelObj == null || jenKelObj.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jenis kelamin harus dipilih", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (golDarObj == null || golDarObj.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Golongan darah harus dipilih", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (dokterObj == null || dokterObj.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dokter harus dipilih", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Konversi nilai combo box ke String setelah validasi null
        String jenKel = jenKelObj.toString().trim();
        String golDar = golDarObj.toString().trim();
        String dokter = dokterObj.toString().trim();

        // Buat ID unik untuk pasien
        String id = pasienController.generateUniqueId(dbConnection.getConnection());

        // Buat model pasien
        PasienModel pasien = new PasienModel(id, nama, tglLahir, noTelpon, email, jenKel, golDar, dokter);

        // Tambah pasien ke database
        if (pasienController.tambahPasien(pasien)) {
            JOptionPane.showMessageDialog(this, "Data pasien berhasil disimpan dengan ID: " + id);
            clearInput();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data pasien", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setupHoverEffect(JPanel button, Color defaultColor, Color hoverColor) {
        button.setBackground(defaultColor);

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(hoverColor);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(defaultColor);
            }
        });
    }

    private void clearInput() {
        txtFieldNama.setText("");
        txtFieldTglLahir.setText("");
        txtFieldHp.setText("");
        txtFieldEmail.setText("");
        comboJenKel.setSelectedIndex(-1);
        comboGolDarah.setSelectedIndex(-1);
        comboDokter.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel cardHeader;
    private javax.swing.JComboBox<String> comboDokter;
    private javax.swing.JComboBox<String> comboGolDarah;
    private javax.swing.JComboBox<String> comboJenKel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelButtonSimpan;
    private javax.swing.JLabel labelInputEmail;
    private javax.swing.JLabel labelInputHP;
    private javax.swing.JLabel labelInputNama;
    private javax.swing.JLabel labelInputTgl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel simpanButton;
    private javax.swing.JLabel titleDaftarPanel;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldHp;
    private javax.swing.JTextField txtFieldNama;
    private javax.swing.JTextField txtFieldTglLahir;
    // End of variables declaration//GEN-END:variables
}
