/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.careHubApps.view.pasien;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.java.com.careHubApps.controller.AntrianController;
import main.java.com.careHubApps.controller.HomeController;
import main.java.com.careHubApps.controller.PasienController;
import main.java.com.careHubApps.model.AntrianModel;
import resources.components.ShadowPanel;
import resources.components.RoundedPanel;
import resources.components.CustomTextField;
import main.java.com.careHubApps.model.PasienModel;
import resources.components.ScrollBarCustom;

/**
 *
 * @author ASUS
 */
public final class PasienPanel extends javax.swing.JPanel{

    PasienModel pasienModel;
    List <PasienModel> pasienList;
    PasienController pasienController;
    AntrianController antrianController;
    AntrianModel antrianModel;
    
    EditPasienView editPasienView;
    
    private boolean isSemuaActive = false;
    private boolean isGigiActive = false;
    private boolean isMataActive = false;
    private boolean isUmumActive = false;
    private boolean isThtActive = false;
    
    /**
     * Creates new form HomePanel
     */
    public PasienPanel() {
        initComponents();
        
        pasienController = new PasienController();
        antrianModel = new AntrianModel();
        antrianController = new AntrianController();

        ScrollBarCustom sb = new ScrollBarCustom();
        jScrollPane2.setVerticalScrollBar(sb);
        
        setupHoverEffect(searchButton, Color.decode("#508D4E"), Color.BLACK);
        setupHoverEffect(refreshButton, Color.decode("#D9D9D9"), Color.BLACK);
        
        setupHoverEffectHead(panelSemua, Color.WHITE, Color.decode("#DFDFDF"));
        setupHoverEffectHead(panelGigi, Color.WHITE, Color.decode("#DFDFDF"));
        setupHoverEffectHead(panelMata, Color.WHITE, Color.decode("#DFDFDF"));
        setupHoverEffectHead(panelTHT, Color.WHITE, Color.decode("#DFDFDF"));
        setupHoverEffectHead(panelUmum, Color.WHITE, Color.decode("#DFDFDF"));
        
        setActiveButton(panelSemua);
        
        
        try {
            File poppinsRegular = new File("src/resources/assets/fonts/Poppins-Regular.ttf");
            File poppinsSemiBold = new File("src/resources/assets/fonts/Poppins-SemiBold.ttf");
            File poppinsBold = new File("src/resources/assets/fonts/Poppins-Bold.ttf");
            
            Font titleTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(20f);
            Font searchTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsRegular).deriveFont(12f);
            Font labelTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsBold).deriveFont(12f);
            Font numberTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsBold).deriveFont(14f);

            titleDatPasien.setFont(titleTxtStyle);
            searchTxtField.setFont(searchTxtStyle);
            
            labelSemua.setFont(labelTxtStyle);
            labelNumberSemua.setFont(numberTxtStyle);
            
            labelGigi.setFont(labelTxtStyle);
            labelNumberGigi.setFont(numberTxtStyle);

            labelUmum.setFont(labelTxtStyle);
            labelNumberUmum.setFont(numberTxtStyle);

            labelTHT.setFont(labelTxtStyle);
            labelNumberTHT.setFont(numberTxtStyle);

            labelMata.setFont(labelTxtStyle);
            labelNumberMata.setFont(numberTxtStyle);
            
        } catch (Exception e){
            e.printStackTrace();
        } 
        
        loadDataPasien();
        updateJumlahPasienPerDokter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new ShadowPanel(8, Color.decode("#DFDFDF"));
        titleDatPasien = new javax.swing.JLabel();
        searchTxtField = new CustomTextField(15, 15, 15, Color.decode("#80AF81"), "Search here", 8);
        searchButton = new RoundedPanel(12, Color.decode("#1A5319"));
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        refreshButton = new RoundedPanel(12, Color.decode("#1A5319"));
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bodyPanel = new RoundedPanel(12, Color.white);
        panelGigi = new ShadowPanel(8, Color.decode("#DFDFDF"));
        labelGigi = new javax.swing.JLabel();
        labelNumberGigi = new javax.swing.JLabel();
        panelUmum = new ShadowPanel(8, Color.decode("#DFDFDF"));
        labelUmum = new javax.swing.JLabel();
        labelNumberUmum = new javax.swing.JLabel();
        panelTHT = new ShadowPanel(8, Color.decode("#DFDFDF"));
        labelTHT = new javax.swing.JLabel();
        labelNumberTHT = new javax.swing.JLabel();
        panelMata = new ShadowPanel(8, Color.decode("#DFDFDF"));
        labelMata = new javax.swing.JLabel();
        labelNumberMata = new javax.swing.JLabel();
        panelSemua = new ShadowPanel(8, Color.decode("#DFDFDF"));
        labelSemua = new javax.swing.JLabel();
        labelNumberSemua = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 720));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleDatPasien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        titleDatPasien.setText("Data Pasien");

        searchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFieldActionPerformed(evt);
            }
        });
        searchTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtFieldKeyTyped(evt);
            }
        });

        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/search_icon.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        searchButton.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/heart_icon.png"))); // NOI18N

        refreshButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });
        refreshButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/refresh_icon.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 30));
        refreshButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(titleDatPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, Short.MAX_VALUE)
                .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addComponent(titleDatPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1000, 70));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane2.setViewportView(bodyPanel);

        mainPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 172, 1010, 470));

        panelGigi.setBackground(new java.awt.Color(255, 255, 255));
        panelGigi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelGigi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGigiMouseClicked(evt);
            }
        });
        panelGigi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelGigi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/tooth_icon.png"))); // NOI18N
        labelGigi.setText("Pasien Gigi");
        labelGigi.setIconTextGap(10);
        panelGigi.add(labelGigi, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 100, 50));

        labelNumberGigi.setForeground(Color.decode("#508D4E")
        );
        labelNumberGigi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberGigi.setText("0");
        panelGigi.add(labelNumberGigi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 50));

        mainPanel.add(panelGigi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 60));

        panelUmum.setBackground(new java.awt.Color(255, 255, 255));
        panelUmum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelUmum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUmumMouseClicked(evt);
            }
        });
        panelUmum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUmum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/stetoscope_icon.png"))); // NOI18N
        labelUmum.setText("Pasien Umum");
        labelUmum.setIconTextGap(10);
        panelUmum.add(labelUmum, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 0, 120, 50));

        labelNumberUmum.setForeground(Color.decode("#508D4E")
        );
        labelNumberUmum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberUmum.setText("0");
        panelUmum.add(labelNumberUmum, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 0, 30, 50));

        mainPanel.add(panelUmum, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 210, 60));

        panelTHT.setBackground(new java.awt.Color(255, 255, 255));
        panelTHT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelTHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTHTMouseClicked(evt);
            }
        });
        panelTHT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTHT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/tht_icon.png"))); // NOI18N
        labelTHT.setText("Pasien THT");
        labelTHT.setIconTextGap(10);
        panelTHT.add(labelTHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 50));

        labelNumberTHT.setForeground(Color.decode("#508D4E")
        );
        labelNumberTHT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberTHT.setText("0");
        panelTHT.add(labelNumberTHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 30, 50));

        mainPanel.add(panelTHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 180, 60));

        panelMata.setBackground(new java.awt.Color(255, 255, 255));
        panelMata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMataMouseClicked(evt);
            }
        });
        panelMata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/eyes_icon.png"))); // NOI18N
        labelMata.setText("Pasien Mata");
        labelMata.setIconTextGap(10);
        panelMata.add(labelMata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 50));

        labelNumberMata.setForeground(Color.decode("#508D4E")
        );
        labelNumberMata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberMata.setText("0");
        panelMata.add(labelNumberMata, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 30, 50));

        mainPanel.add(panelMata, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 180, 60));

        panelSemua.setBackground(new java.awt.Color(255, 255, 255));
        panelSemua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelSemua.setPreferredSize(new java.awt.Dimension(200, 50));
        panelSemua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSemuaMouseClicked(evt);
            }
        });
        panelSemua.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSemua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSemua.setText("Semua");
        labelSemua.setIconTextGap(10);
        panelSemua.add(labelSemua, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, 60, 50));

        labelNumberSemua.setForeground(Color.decode("#508D4E")
        );
        labelNumberSemua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberSemua.setText("0");
        panelSemua.add(labelNumberSemua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 41, 50));

        mainPanel.add(panelSemua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 60));

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_searchButtonMouseClicked

    private void searchTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtFieldKeyTyped
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_searchTxtFieldKeyTyped

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        // TODO add your handling code here:
        loadDataPasien();
        setActiveButton(panelSemua);
        updateJumlahPasienPerDokter();
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void panelGigiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGigiMouseClicked
        // TODO add your handling code here:
         List<PasienModel> filteredPatients = pasienList.stream()
                .filter(p -> p.getLayanan().toLowerCase().contains("gigi"))
                .collect(Collectors.toList());
         
         displayPatients(filteredPatients);
         
         setActiveButton(panelGigi);
    }//GEN-LAST:event_panelGigiMouseClicked

    private void panelUmumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUmumMouseClicked
        // TODO add your handling code here:
        List<PasienModel> filteredPatients = pasienList.stream()
                .filter(p -> p.getLayanan().toLowerCase().contains("umum"))
                .collect(Collectors.toList());
         
         displayPatients(filteredPatients);
         
         setActiveButton(panelUmum);
    }//GEN-LAST:event_panelUmumMouseClicked

    private void panelTHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTHTMouseClicked
        // TODO add your handling code here:
        List<PasienModel> filteredPatients = pasienList.stream()
                .filter(p -> p.getLayanan().toLowerCase().contains("tht"))
                .collect(Collectors.toList());
         
         displayPatients(filteredPatients);
         
         setActiveButton(panelTHT);
    }//GEN-LAST:event_panelTHTMouseClicked

    private void panelMataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMataMouseClicked
        // TODO add your handling code here:
        List<PasienModel> filteredPatients = pasienList.stream()
                .filter(p -> p.getLayanan().toLowerCase().contains("mata"))
                .collect(Collectors.toList());
         
         displayPatients(filteredPatients);
         
         setActiveButton(panelMata);
    }//GEN-LAST:event_panelMataMouseClicked

    private void panelSemuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSemuaMouseClicked
        // TODO add your handling code here:
        loadDataPasien();
        setActiveButton(panelSemua);
    }//GEN-LAST:event_panelSemuaMouseClicked

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    private void setActiveButton(JPanel activeButton) {
        isSemuaActive = activeButton == panelSemua;
        isGigiActive = activeButton == panelGigi;
        isUmumActive = activeButton == panelUmum;
        isMataActive = activeButton == panelMata;
        isThtActive = activeButton == panelTHT;
        
        
        JPanel[] buttons = {panelSemua, panelGigi, panelUmum, panelMata, panelTHT};
        Color defaultColor = Color.decode("#FFFFFF");
        Color activeColor = Color.decode("#DFDFDF");

        for (JPanel button : buttons) {
            if (button == activeButton) {
                button.setBackground(activeColor);
            } else {
                button.setBackground(defaultColor);
            }
        }
    }
    
    private void setupHoverEffectHead(JPanel button, Color defaultColor, Color hoverColor) {
        button.setBackground(defaultColor);

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if ((button == panelSemua && !isSemuaActive) ||
                    (button == panelGigi && !isGigiActive) ||
                    (button == panelMata && !isMataActive) ||
                    (button == panelTHT && !isThtActive) ||
                    (button == panelUmum && !isUmumActive)) {
                        button.setBackground(hoverColor);
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if ((button == panelSemua && !isSemuaActive) ||
                    (button == panelGigi && !isGigiActive) ||
                    (button == panelMata && !isMataActive) ||
                    (button == panelTHT && !isThtActive) ||
                    (button == panelUmum && !isUmumActive)) {
                        button.setBackground(defaultColor);
                }
            }
        });
    }
    
    private void setupHoverEffect(JPanel button, Color defaultColor, Color hoverColor) {
        button.setBackground(defaultColor);

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(hoverColor);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(defaultColor);
            }
        });
    }
    
    private void performSearch() {
        String searchText = searchTxtField.getText().trim().toLowerCase();
        
        if (searchText.isEmpty()) {
            loadDataPasien();
            displayPatients(pasienList);
        } else {
            List<PasienModel> filteredPatients = pasienList.stream()
                .filter(p -> p.getNama().toLowerCase().contains(searchText) ||
                             p.getNoTelpon().toLowerCase().contains(searchText) ||
                             p.getJenisKelamin().toLowerCase().contains(searchText) ||
                             p.getLayanan().toLowerCase().contains(searchText) ||
                             p.getId().toLowerCase().contains(searchText))
                .collect(Collectors.toList());
            
            if (filteredPatients.isEmpty()) {
                displayNoDataFound();
            } else {
                displayPatients(filteredPatients);
            }
        }   
        
        isGigiActive = false;
        isUmumActive = false;
        isMataActive = false;
        isThtActive = false;
    }
    
    private void displayNoDataFound() {
        bodyPanel.removeAll();

        JLabel noDataLabel = new JLabel("Maaf, " + "`" + searchTxtField.getText().trim() + "`" + " tidak ditemukan.");
        JLabel noDataImage = new JLabel();

        noDataImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/not_found.png")));

        try {
            File poppinsSemiBold = new File("src/resources/assets/fonts/Poppins-SemiBold.ttf");
            Font labelTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(16f);
            noDataLabel.setFont(labelTxtStyle);
            noDataLabel.setForeground(Color.decode("#508D4E"));
        } catch (Exception e){
            e.printStackTrace();
        }

        noDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noDataImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bodyPanel.setLayout(null);  // Set layout to null for AbsoluteLayout
        bodyPanel.setBounds(0, 0, 1040, 400);


        int imageWidth = 128;  // Adjust this to the actual width of your image
        int imageHeight = 128; // Adjust this to the actual height of your image
        int labelHeight = 30;  // Height of the label
        int panelWidth = bodyPanel.getWidth();
        int panelHeight = bodyPanel.getHeight();

        int imageX = (panelWidth - imageWidth) / 2;
        int imageY = (panelHeight - imageHeight - labelHeight) / 2;
        int labelX = (panelWidth - noDataLabel.getPreferredSize().width) / 2;
        int labelY = imageY + imageHeight + 10;

        noDataImage.setBounds(imageX, imageY, imageWidth, imageHeight);
        noDataLabel.setBounds(labelX, labelY, noDataLabel.getPreferredSize().width, labelHeight);

        bodyPanel.add(noDataImage);
        bodyPanel.add(noDataLabel);

        bodyPanel.revalidate();
        bodyPanel.repaint();
    }
    
    private void emptyDataDisplay(){
        bodyPanel.removeAll();
        
        JLabel noDataLabel = new JLabel("Tidak Ada Pasien");
        JLabel noDataImage = new JLabel();

        noDataImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/thinking.png")));

        try {
            File poppinsSemiBold = new File("src/resources/assets/fonts/Poppins-SemiBold.ttf");
            Font labelTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(16f);
            noDataLabel.setFont(labelTxtStyle);
            noDataLabel.setForeground(Color.decode("#508D4E"));
        } catch (Exception e){
            e.printStackTrace();
        }

        noDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noDataImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bodyPanel.setLayout(null);  // Set layout to null for AbsoluteLayout
        bodyPanel.setBounds(0, 0, 1040, 400);
        
        int imageWidth = 128;  // Adjust this to the actual width of your image
        int imageHeight = 128; // Adjust this to the actual height of your image
        int labelHeight = 30;  // Height of the label
        int panelWidth = bodyPanel.getWidth();
        int panelHeight = bodyPanel.getHeight();

        int imageX = (panelWidth - imageWidth) / 2 ;
        int imageY = (panelHeight - imageHeight - labelHeight) / 2;
        int labelX = (panelWidth - noDataLabel.getPreferredSize().width) / 2;
        int labelY = imageY + imageHeight + 10;

        noDataImage.setBounds(imageX, imageY, imageWidth, imageHeight);
        noDataLabel.setBounds(labelX, labelY, noDataLabel.getPreferredSize().width, labelHeight);

        bodyPanel.add(noDataImage);
        bodyPanel.add(noDataLabel);

        bodyPanel.revalidate();
        bodyPanel.repaint();
    }
    
    public void loadDataPasien() {
        this.pasienList = pasienController.getAllPatients(); 
        if (pasienList == null || pasienList.isEmpty()) {
            emptyDataDisplay();
        } else {
            displayPatients(pasienList);
        }
    }
   
   private void displayPatients(List<PasienModel> patients) {
    bodyPanel.removeAll(); // Clear existing components
    bodyPanel.repaint();
    bodyPanel.revalidate();

    if (patients == null || patients.isEmpty()) {
        emptyDataDisplay();
    } else {
        bodyPanel.setLayout(null); // Use absolute layout

        int x = 20, y = 20;
        int cardWidth = 440, cardHeight = 420;
        int padding = 20;
        int cardsPerRow = 2; // Number of cards per row

        for (int i = 0; i < patients.size(); i++) {
            PasienModel pasien = patients.get(i);
            ShadowPanel cardPasien = new ShadowPanel(8, Color.decode("#DFDFDF"));
            cardPasien.setBackground(Color.WHITE);
            cardPasien.setBounds(x, y, cardWidth, cardHeight); // Set position and size

            JLabel labelId = new JLabel("ID: " + pasien.getId());
            JLabel titleNama = new JLabel("Nama Pasien");
            JLabel labelNama = new JLabel(pasien.getNama());
            JLabel titleTelpon = new JLabel("No Telpon");
            JLabel labelTelpon = new JLabel(pasien.getNoTelpon());
            JLabel titleJenKel = new JLabel("Jenis Kelamin");
            JLabel labelJenKel = new JLabel(pasien.getJenisKelamin());
            JLabel titleDokter = new JLabel("Layanan");
            JLabel labelDokter = new JLabel(pasien.getLayanan());

            RoundedPanel buttonAntrian = new RoundedPanel(12, Color.decode("#508D4E"));
            JLabel buttonLabel = new JLabel("Tambah ke Antrian");
            buttonLabel.setForeground(Color.WHITE); // Set text color
            buttonAntrian.add(buttonLabel);
            buttonAntrian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

            RoundedPanel buttonEdit = new RoundedPanel(12, Color.white);
            JLabel editLabel = new JLabel("Edit Pasien");
            editLabel.setForeground(Color.decode("#508D4E")); // Set text color
            buttonEdit.add(editLabel);
            buttonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

            RoundedPanel buttonHapus = new RoundedPanel(12, Color.white);
            JLabel hapusLabel = new JLabel("Hapus Pasien");
            hapusLabel.setForeground(Color.RED); // Set text color
            buttonHapus.add(hapusLabel);
            buttonHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

            setupHoverEffect(buttonAntrian, Color.decode("#508D4E"), Color.BLACK);
            setupHoverEffect(buttonEdit, Color.WHITE, Color.BLACK);
            setupHoverEffect(buttonHapus, Color.WHITE, Color.RED);

            buttonAntrian.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    antrianModel.setId_pasien(pasien.getId());
                    antrianModel.setNama(pasien.getNama());
                    antrianModel.setLayanan(pasien.getLayanan());

                    antrianController.tambahAntrian(antrianModel);
                    JOptionPane.showMessageDialog(mainPanel, "Berhasil Menambahkan ke Antrian", "SUKSES", 1);
                }
            });

            buttonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    editLabel.setForeground(Color.WHITE);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    editLabel.setForeground(Color.decode("#508D4E"));
                }

                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    editPasienView = new EditPasienView(pasien);
                    editPasienView.setVisible(true);
                }
            });

            buttonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    hapusLabel.setForeground(Color.WHITE);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    hapusLabel.setForeground(Color.RED);
                }

                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus pasien " + pasien.getNama(), "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (response == JOptionPane.YES_OPTION) {
                        pasienController.hapusPasien(pasien.getId());

                        loadDataPasien();
                        updateJumlahPasienPerDokter();
                    }
                }
            });

            try {
                File poppinsSemiBold = new File("src/resources/assets/fonts/Poppins-SemiBold.ttf");
                File poppinsBold = new File("src/resources/assets/fonts/Poppins-Bold.ttf");

                Font cardTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsSemiBold).deriveFont(14f);
                Font titleTxtStyle = Font.createFont(Font.TRUETYPE_FONT, poppinsBold).deriveFont(12f);

                titleNama.setFont(titleTxtStyle);
                titleNama.setForeground(Color.decode("#508D4E"));
                titleTelpon.setFont(titleTxtStyle);
                titleTelpon.setForeground(Color.decode("#508D4E"));
                titleJenKel.setFont(titleTxtStyle);
                titleJenKel.setForeground(Color.decode("#508D4E"));
                titleDokter.setFont(titleTxtStyle);
                titleDokter.setForeground(Color.decode("#508D4E"));

                labelId.setForeground(Color.decode("#508D4E"));
                labelId.setFont(titleTxtStyle);
                labelNama.setFont(cardTxtStyle);
                labelTelpon.setFont(cardTxtStyle);
                labelJenKel.setFont(cardTxtStyle);
                labelDokter.setFont(cardTxtStyle);
                buttonLabel.setFont(cardTxtStyle);
                hapusLabel.setFont(cardTxtStyle);
                editLabel.setFont(cardTxtStyle);

            } catch (Exception e) {
                e.printStackTrace();
            }

            buttonAntrian.setPreferredSize(new java.awt.Dimension(390, 36));
            buttonHapus.setPreferredSize(new java.awt.Dimension(390, 36));
            buttonEdit.setPreferredSize(new java.awt.Dimension(390, 36));

            cardPasien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            cardPasien.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
            cardPasien.add(titleNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
            cardPasien.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
            cardPasien.add(titleTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
            cardPasien.add(labelTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
            cardPasien.add(titleJenKel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
            cardPasien.add(labelJenKel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
            cardPasien.add(titleDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
            cardPasien.add(labelDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
            cardPasien.add(buttonAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
            cardPasien.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
            cardPasien.add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

            bodyPanel.add(cardPasien);

            if ((i + 1) % cardsPerRow == 0) {
                x = 20;
                y += cardHeight + padding;
            } else {
                x += cardWidth + padding;
            }
        }

        bodyPanel.setPreferredSize(new Dimension(bodyPanel.getWidth(), y + cardHeight + padding));
        bodyPanel.revalidate();
        bodyPanel.repaint();
    }
}

   
     private void updateJumlahPasienPerDokter() {
        Map<String, Integer> jumlahPasienPerDokter = pasienController.getJumlahPasienPerLayanan();
        
        HomeController homeController = new HomeController();
        
        labelNumberSemua.setText(String.valueOf(homeController.hitungPasien()));
        labelNumberGigi.setText(String.valueOf(jumlahPasienPerDokter.getOrDefault("Gigi", 0)));
        labelNumberUmum.setText(String.valueOf(jumlahPasienPerDokter.getOrDefault("Umum", 0)));
        labelNumberTHT.setText(String.valueOf(jumlahPasienPerDokter.getOrDefault("THT", 0)));
        labelNumberMata.setText(String.valueOf(jumlahPasienPerDokter.getOrDefault("Mata", 0)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelGigi;
    private javax.swing.JLabel labelMata;
    private javax.swing.JLabel labelNumberGigi;
    private javax.swing.JLabel labelNumberMata;
    private javax.swing.JLabel labelNumberSemua;
    private javax.swing.JLabel labelNumberTHT;
    private javax.swing.JLabel labelNumberUmum;
    private javax.swing.JLabel labelSemua;
    private javax.swing.JLabel labelTHT;
    private javax.swing.JLabel labelUmum;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelGigi;
    private javax.swing.JPanel panelMata;
    private javax.swing.JPanel panelSemua;
    private javax.swing.JPanel panelTHT;
    private javax.swing.JPanel panelUmum;
    private javax.swing.JPanel refreshButton;
    private javax.swing.JPanel searchButton;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JLabel titleDatPasien;
    // End of variables declaration//GEN-END:variables
}
