package main.java.com.careHubApps.view;

import java.awt.Color;
import resources.components.ShadowPanel;

/**
 *
 * @author ASUS
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public AboutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new ShadowPanel(8, Color.decode("#DFDFDF"));
        titleDataObat = new javax.swing.JLabel();
        cardZaki = new ShadowPanel(6, Color.decode("#DFDFDF"));
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cardZaki1 = new ShadowPanel(6, Color.decode("#DFDFDF"));
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cardZaki2 = new ShadowPanel(6, Color.decode("#DFDFDF"));
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cardZaki3 = new ShadowPanel(6, Color.decode("#DFDFDF"));
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cardZaki4 = new ShadowPanel(6, Color.decode("#DFDFDF"));
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 1080));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleDataObat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        titleDataObat.setText("Meet Our Team");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleDataObat)
                .addContainerGap(825, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(titleDataObat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1000, 70));

        cardZaki.setBackground(new java.awt.Color(255, 255, 255));
        cardZaki.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/dimas.png"))); // NOI18N
        cardZaki.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("10123206");
        cardZaki.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Muhammad Dimas H P");
        cardZaki.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        mainPanel.add(cardZaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 190, 260));

        cardZaki1.setBackground(new java.awt.Color(255, 255, 255));
        cardZaki1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/topik.png"))); // NOI18N
        cardZaki1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("10123206");
        cardZaki1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Topik Nur Rahman");
        cardZaki1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        mainPanel.add(cardZaki1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 190, 260));

        cardZaki2.setBackground(new java.awt.Color(255, 255, 255));
        cardZaki2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/zaki.png"))); // NOI18N
        cardZaki2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("10123206");
        cardZaki2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mohamad Zaki Zakiran");
        cardZaki2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        mainPanel.add(cardZaki2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 260));

        cardZaki3.setBackground(new java.awt.Color(255, 255, 255));
        cardZaki3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/fariq.png"))); // NOI18N
        cardZaki3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("10123206");
        cardZaki3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 20));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fariq Daffa");
        cardZaki3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        mainPanel.add(cardZaki3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 190, 260));

        cardZaki4.setBackground(new java.awt.Color(255, 255, 255));
        cardZaki4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/ardi.png"))); // NOI18N
        cardZaki4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("10123206");
        cardZaki4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ardi Saputra");
        cardZaki4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        mainPanel.add(cardZaki4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 190, 260));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/team.png"))); // NOI18N
        mainPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardZaki;
    private javax.swing.JPanel cardZaki1;
    private javax.swing.JPanel cardZaki2;
    private javax.swing.JPanel cardZaki3;
    private javax.swing.JPanel cardZaki4;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel titleDataObat;
    // End of variables declaration//GEN-END:variables
}
